---
# Configuration tasks

- name: configure rpmfusion repositories
  ini_file:
    path: "/etc/yum.repos.d/rpmfusion-{{ item.0 + '.repo' }}"
    section: "{{ 'rpmfusion-' + item.0 + item.1 }}"
    option: "enabled"
    value: >-
      {{ inventory['rpmfusion_'
                   + item.0 | regex_replace("-", "_")
                   + '_enabled']
         | default(vars['rpmfusion_'
                        + item.0 | regex_replace("-", "_")
                        + '_enabled']) }}
    no_extra_spaces: true
  with_nested:
    - [ free,
        free-updates,
        free-updates-testing,
        nonfree,
        nonfree-updates,
        nonfree-updates-testing ]
    - [ '', '-debuginfo', '-source']
  when: rpmfusion_state=="present"
  loop_control:
    label: "{{ 'rpmfusion-' + item.0 + item.1 }}"
  vars:
    inventory: hostvars[inventory_hostname]
  tags:
    - role::rpmfusion
    - role::rpmfusion::configure
