---
# Install tasks

- block:
    - name: Search rpmfusion installed packages
      shell: >-
        rpm -q --queryformat "%{NAME}\n"
        {{ rpmfusion_package | regex_replace('.noarch.rpm', '') }}
      args:
        warn: no
      register: rpmfusion_check_packages_result
      changed_when: no
      failed_when: no
      loop: "{{ rpmfusion_variants }}"

    - block:
        - block:
            - name: Download rpmfusion repository packages
              get_url:
                url: >-
                  {{ rpmfusion_url
                     + "/"
                     + item
                     + "/"
                     + rpmfusion_distro
                     + "/"
                     + rpmfusion_package }}
                dest: "{{ rpmfusion_download_tmp_dir }}"
                validate_certs: "{{ rpmfusion_validate_certs | bool }}"
              loop: "{{ rpmfusion_variants }}"
              environment: "{{ proxy_client_environment }}"

            - name: Install rpmfusion repository packages
              package:
                name: "{{ rpmfusion_package_download_path }}"
                state: present
                disable_gpg_check: "{{ not rpmfusion_validate_certs | bool }}"
              loop: "{{ rpmfusion_variants }}"
          when:
            (rpmfusion_state == "present"
              and rpmfusion_package_name not in rpmfusion_installed_packages)
            or rpmfusion_state == "force"

        - name: Uninstall rpmfusion repository packages
          package:
            name: "{{ item | regex_replace('-27-1.noarch', '') }}"
            state: absent
          when: rpmfusion_state == "absent"
          loop: "{{ rpmfusion_installed_packages }}"

        - name: Delete rpmfusion repository downloaded packages
          file:
            path: "{{ rpmfusion_package_download_path }}"
            state: absent
          loop: "{{ rpmfusion_variants }}"
      vars:
        rpmfusion_installed_packages: >-
          {{ rpmfusion_check_packages_result.results
             | selectattr('rc', 'equalto', 0)
             | map(attribute='stdout_lines')
             | list
             | sum(start=[]) }}
  vars:
    rpmfusion_distro: >-
      {{ (ansible_facts.distribution | lower != "fedora")
         | ternary("el", "fedora") }}
    rpmfusion_package_name: >-
      {{ "rpmfusion-"
         + item
         + "-release" }}
    rpmfusion_package: >-
      {{ rpmfusion_package_name
         + "-"
         + ansible_facts.distribution_major_version
         + ".noarch.rpm" }}
    rpmfusion_package_download_path: >-
      {{ rpmfusion_download_tmp_dir
         + "/"
         + rpmfusion_package }}

  tags:
    - role::rpmfusion
    - role::rpmfusion::packages
    - role::rpmfusion::install
