---
# Install tasks

- name: setup python required packages
  package:
    name: "{{ item }}"
    state: present
  when:
    - rpmfusion_state == "present"
    - ansible_distribution | lower in ["centos", "rhel"]
    - ansible_distribution_major_version == "6"
  with_items:
    - python-urllib3
    - pyOpenSSL
    - python-ndg_httpsclient
    - python-pyasn1

- name: setup rpmfusion repository packages
  package:
    name: >-
      {{ (rpmfusion_state == "present")
         | (ternary,
            rpmfusion_url
            + "/"
            + item
            + "/"
            + distro
            + "/rpmfusion-"
            + item
            + "-release-"
            + ansible_distribution_major_version
            + ".noarch.rpm",

            "rpmfusion-"
            + item
            + "-release-"
            + ansible_distribution_major_version) }}
    state: "{{ rpmfusion_state }}"
  with_items:
    - "free"
    - "nonfree"
  loop_control:
    label: >-
      rpmfusion-{{ item }}-release-{{ ansible_distribution_major_version }}
  vars:
    distro: >-
      {{ (ansible_distribution | lower != "fedora") | ternary("el", "fedora") }}
  tags:
    - role::rpmfusion
    - role::rpmfusion::packages
    - role::rpmfusion::install
