---
# Install tasks

- name: install rpmfusion repository packages
  package:
    name: >-
      {{ rpmfusion_url
         + "/"
         + item
         + "/"
         + distro
         + "/rpmfusion-"
         + item
         + "-release-"
         + ansible_distribution_major_version
         + ".noarch.rpm" }}
    state: "{{ rpmfusion_state }}"
  with_items:
    - "free"
    - "nonfree"
  vars:
    distro: >-
      {{ (ansible_distribution | lower != "fedora") | ternary("el", "fedora") }}
  tags:
    - role::rpmfusion
    - role::rpmfusion::packages
    - role::rpmfusion::install
