---
# Role tasks

- name: Install rpmfusion repository
  include_tasks: install.yml
  tags:
    - role::rpmfusion
    - role::rpmfusion::install

- name: Configure rpmfusion repository
  include_tasks: configure.yml
  tags:
    - role::rpmfusion
    - role::rpmfusion::configure
