---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      fedora: 29
      rhel: 6

- role:
    name: amtega.epel
  when: ansible_facts.distribution_major_version == "6"

- include_role:
    name: amtega.packages
  vars:
    packages_os:
      centos:
        all:
          yum: present
        6:
          python-urllib3: present
          pyOpenSSL: present
          python-ndg_httpsclient: present
          python-pyasn1: present
      fedora:
        all:
          yum: present
      rhel:
        all:
          yum: present
        6:
          python-urllib3: present
          pyOpenSSL: present
          python-ndg_httpsclient: present
          python-pyasn1: present
    packages_python:
      all:
        all:
          "python-gitlab>=1.6": latest
          PyYaml: present

- include_role:
    name: amtega.proxy_client
  vars:
    proxy_client_permanent: no

- name: Install rpmfusion repository
  include_tasks: install.yml
  tags:
    - role::rpmfusion
    - role::rpmfusion::install

- name: Configure rpmfusion repository
  include_tasks: configure.yml
  tags:
    - role::rpmfusion
    - role::rpmfusion::configure
