---

- name: Verify
  hosts: molecule_hosts
  tasks:
    - name: Check that all rpmfusion packages were removed
      shell: >-
        set -o pipefail ;
        rpm -qa | grep rpmfusion
      args:
        warn: no
      register: check_packages
      failed_when: check_packages.stdout | length > 0
      changed_when: no
