---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
provisioner:
  name: ansible
  playbooks:
    cleanup: ../resources/cleanup.yml
    cleanup: ../resources/converge.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    side_effect: ../resources/side_effect.yml
    verify: ../resources/verify.yml
  inventory:
    hosts:
      molecule_hosts:
        vars:
          rpmfusion_state: force

          rpmfusion_free_enabled: 1
          rpmfusion_free_debuginfo_enabled: 1
          rpmfusion_free_source_enabled: 1

          rpmfusion_free_updates_enabled: 1
          rpmfusion_free_updates_debuginfo_enabled: 1
          rpmfusion_free_updates_source_enabled: 1

          rpmfusion_free_updates_testing_enabled: 1
          rpmfusion_free_updates_testing_debuginfo_enabled: 1
          rpmfusion_free_updates_testing_source_enabled: 1

          rpmfusion_free_rawhide_enabled: 1
          rpmfusion_free_rawhide_debuginfo_enabled: 1
          rpmfusion_free_rawhide_source_enabled: 1

          rpmfusion_nonfree_enabled: 1
          rpmfusion_nonfree_debuginfo_enabled: 1
          rpmfusion_nonfree_source_enabled: 1

          rpmfusion_nonfree_updates_enabled: 1
          rpmfusion_nonfree_updates_debuginfo_enabled: 1
          rpmfusion_nonfree_updates_source_enabled: 1

          rpmfusion_nonfree_updates_testing_enabled: 1
          rpmfusion_nonfree_updates_testing_debuginfo_enabled: 1
          rpmfusion_nonfree_updates_testing_source_enabled: 1

          rpmfusion_nonfree_rawhide_enabled: 1
          rpmfusion_nonfree_rawhide_debuginfo_enabled: 1
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
